!include theme-common.puml

skinparam TitleFontColor #171716
skinparam ArrowColor #676665
skinparam ArrowFontColor #676665
skinparam ComponentBackgroundColor #e8e5df
skinparam ComponentBorderColor #676665
skinparam ComponentFontColor #171716
skinparam DatabaseBackgroundColor #eee6ea
skinparam DatabaseBorderColor ACCENT
skinparam DatabaseFontColor #171716
skinparam QueueBackgroundColor #eee6ea
skinparam QueueBorderColor ACCENT
skinparam QueueFontColor #171716
skinparam ActorBackgroundColor #f2f0eb
skinparam ActorBorderColor ACCENT
skinparam ActorFontColor #171716
skinparam ArtifactBackgroundColor #e8e5df
skinparam ArtifactBorderColor #676665
skinparam ArtifactFontColor #171716
